# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather_project_MVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'Moya'
  pod 'PromiseKit'
  pod 'RealmSwift'
  pod 'SwiftLint'
  pod 'Locksmith'
  # Pods for Weather_project_MVP

end

target 'Weather_project_MVPTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Weather_project_MVPUITests' do
  # Pods for testing
end
